train_dataset_cfg:
  name: prosab_ct
  kwargs:
    index_file_path: C:\Users\thendriks\code\git_repositories\base_project\input_files\nifti_input_train_csv.csv
train_dataloader_cfg:
  batch_size: 2
  shuffle: True
  num_workers: 4
  drop_last: False

val_dataset_cfg:
  name: prosab_ct
  kwargs:
    index_file_path: C:\Users\thendriks\code\git_repositories\base_project\input_files\nifti_input_val_csv.csv
val_dataloader_cfg:
  batch_size: 5
  shuffle: False
  num_workers: 4
  drop_last: False

trainer_cfg:
  name: base_trainer

model_cfg:
  name: medical_net50
  kwargs:
    pretrain: True
    weights_path: C:\Users\thendriks\code\git_repositories\base_project\models\weights\resnet_50_23dataset.pth
    input_shape: [128, 256, 256]
    n_classes: 1

loss_cfg:
  name: bce_logits

optimizer_cfg:
  name: adam
  kwargs:
    lr: 0.00005

session_cfg:
  epochs: 10

log_cfg:
  wandb_init:
    project: base_project
    job_type: prototype
  log_fns: ['loss_train_step', 'loss_train_epoch', 'loss_val_epoch', 'bi_acc_val_epoch']