train_dataset_cfg:
  name: mock_image
  kwargs:
    size: 10
    image_size: [3,256,256]
    classes: 1000
train_dataloader_cfg:
  batch_size: 2
  shuffle: True
  num_workers: 4
  drop_last: False

val_dataset_cfg:
  name: mock_image
  kwargs:
    size: 2
    image_size: [3,256,256]
    classes: 1000
val_dataloader_cfg:
  batch_size: 2
  shuffle: False
  num_workers: 4
  drop_last: False

trainer_cfg:
  name: base_trainer

model_cfg:
  name: test_resnet
  kwargs:
    weights: null

loss_cfg:
  name: ce_logits

optimizer_cfg:
  name: adam
  kwargs:
    lr: 0.0001

session_cfg:
  epochs: 1
  metrics: ['loss_train_step', 'acc_train_epoch', 'acc_val_epoch'] #training and validation loss alway logged on epoch
# selection metric: loss_val_epoch # NOTE: only epoch based metrics are supported for selection
# goal: minimize

log_cfg:
  wandb_init:
    project: base_project
    job_type: prototype